package com.cyj.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSections<M extends BaseSections<M>> extends Model<M> implements IBean {

	public M setSectionsId(java.lang.Long sectionsId) {
		set("sections_id", sectionsId);
		return (M)this;
	}
	
	public java.lang.Long getSectionsId() {
		return getLong("sections_id");
	}

	public M setSectionsName(java.lang.String sectionsName) {
		set("sections_name", sectionsName);
		return (M)this;
	}
	
	public java.lang.String getSectionsName() {
		return getStr("sections_name");
	}

	public M setSectionsRemark(java.lang.String sectionsRemark) {
		set("sections_remark", sectionsRemark);
		return (M)this;
	}
	
	public java.lang.String getSectionsRemark() {
		return getStr("sections_remark");
	}

}
