package com.cyj.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseConsumelogs<M extends BaseConsumelogs<M>> extends Model<M> implements IBean {

	public M setConsumelogsId(java.lang.Long consumelogsId) {
		set("consumelogs_id", consumelogsId);
		return (M)this;
	}
	
	public java.lang.Long getConsumelogsId() {
		return getLong("consumelogs_id");
	}

	public M setConsumelogsCardno(java.lang.String consumelogsCardno) {
		set("consumelogs_cardNo", consumelogsCardno);
		return (M)this;
	}
	
	public java.lang.String getConsumelogsCardno() {
		return getStr("consumelogs_cardNo");
	}

	public M setReadRoomId(java.lang.Integer readRoomId) {
		set("readRoomId", readRoomId);
		return (M)this;
	}
	
	public java.lang.Integer getReadRoomId() {
		return getInt("readRoomId");
	}

	public M setConsumelogsIntime(java.util.Date consumelogsIntime) {
		set("consumelogs_inTime", consumelogsIntime);
		return (M)this;
	}
	
	public java.util.Date getConsumelogsIntime() {
		return get("consumelogs_inTime");
	}

	public M setConsumelogsOuttime(java.util.Date consumelogsOuttime) {
		set("consumelogs_outTime", consumelogsOuttime);
		return (M)this;
	}
	
	public java.util.Date getConsumelogsOuttime() {
		return get("consumelogs_outTime");
	}

	public M setConsumelogsStatus(java.lang.Integer consumelogsStatus) {
		set("consumelogs_status", consumelogsStatus);
		return (M)this;
	}
	
	public java.lang.Integer getConsumelogsStatus() {
		return getInt("consumelogs_status");
	}
	
	/**
	 * 辅助字段用来获取资源使用次数
	 * @param statistics_peopleNums
	 * @return
	 */
	public Integer SetStatistics_peopleNums(java.lang.Integer statistics_peopleNums) {
		return getInt("statistics_peopleNums");
	}
	/**
	 * 辅助字段用来获取资源使用次数
	 * @param statistics_peopleNums
	 * @return
	 */
	public java.lang.Integer getStatistics_peopleNums() {
		return getInt("statistics_peopleNums");
	}

}
