package com.cyj.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseReadrooms<M extends BaseReadrooms<M>> extends Model<M> implements IBean {

	public M setReadroomsId(java.lang.Integer readroomsId) {
		set("readrooms_id", readroomsId);
		return (M)this;
	}
	
	public java.lang.Integer getReadroomsId() {
		return getInt("readrooms_id");
	}

	public M setReadroomsName(java.lang.String readroomsName) {
		set("readrooms_name", readroomsName);
		return (M)this;
	}
	
	public java.lang.String getReadroomsName() {
		return getStr("readrooms_name");
	}

	public M setReadroomsRemark(java.lang.String readroomsRemark) {
		set("readrooms_remark", readroomsRemark);
		return (M)this;
	}
	
	public java.lang.String getReadroomsRemark() {
		return getStr("readrooms_remark");
	}

}
