package com.cyj.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTeachers<M extends BaseTeachers<M>> extends Model<M> implements IBean {

	public M setTeachersId(java.lang.Long teachersId) {
		set("teachers_id", teachersId);
		return (M)this;
	}
	
	public java.lang.Long getTeachersId() {
		return getLong("teachers_id");
	}

	public M setTeachersCardno(java.lang.String teachersCardno) {
		set("teachers_cardNo", teachersCardno);
		return (M)this;
	}
	
	public java.lang.String getTeachersCardno() {
		return getStr("teachers_cardNo");
	}

	public M setTeachersName(java.lang.String teachersName) {
		set("teachers_name", teachersName);
		return (M)this;
	}
	
	public java.lang.String getTeachersName() {
		return getStr("teachers_name");
	}

	public M setTeachersSex(java.lang.String teachersSex) {
		set("teachers_sex", teachersSex);
		return (M)this;
	}
	
	public java.lang.String getTeachersSex() {
		return getStr("teachers_sex");
	}

	public M setSectionID(java.lang.Long sectionID) {
		set("sectionID", sectionID);
		return (M)this;
	}
	
	public java.lang.Long getSectionID() {
		return getLong("sectionID");
	}

	public M setTeachersStatus(java.lang.Integer teachersStatus) {
		set("teachers_status", teachersStatus);
		return (M)this;
	}
	
	public java.lang.Integer getTeachersStatus() {
		return getInt("teachers_status");
	}

	public M setTeachersRemark(java.lang.String teachersRemark) {
		set("teachers_remark", teachersRemark);
		return (M)this;
	}
	
	public java.lang.String getTeachersRemark() {
		return getStr("teachers_remark");
	}

}
