package com.cyj.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseStatistics<M extends BaseStatistics<M>> extends Model<M> implements IBean {

	public M setStatisticsId(java.lang.Long statisticsId) {
		set("statistics_id", statisticsId);
		return (M)this;
	}
	
	public java.lang.Long getStatisticsId() {
		return getLong("statistics_id");
	}

	public M setReadRoomId(java.lang.Long readRoomId) {
		set("readRoomId", readRoomId);
		return (M)this;
	}
	
	public java.lang.Long getReadRoomId() {
		return getLong("readRoomId");
	}

	public M setStatisticsPeoplenums(java.lang.Integer statisticsPeoplenums) {
		set("statistics_peopleNums", statisticsPeoplenums);
		return (M)this;
	}
	
	public java.lang.Integer getStatisticsPeoplenums() {
		return getInt("statistics_peopleNums");
	}

	public M setStatisticsYear(java.lang.String statisticsYear) {
		set("statistics_year", statisticsYear);
		return (M)this;
	}
	
	public java.lang.String getStatisticsYear() {
		return getStr("statistics_year");
	}

	public M setStatisticsMonth(java.lang.String statisticsMonth) {
		set("statistics_month", statisticsMonth);
		return (M)this;
	}
	
	public java.lang.String getStatisticsMonth() {
		return getStr("statistics_month");
	}

	public M setStatisticsDay(java.lang.String statisticsDay) {
		set("statistics_day", statisticsDay);
		return (M)this;
	}
	
	public java.lang.String getStatisticsDay() {
		return getStr("statistics_day");
	}
	
}
