package com.cyj.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseMemberships<M extends BaseMemberships<M>> extends Model<M> implements IBean {

	public M setMembershipsId(java.lang.Long membershipsId) {
		set("memberships_id", membershipsId);
		return (M)this;
	}
	
	public java.lang.Long getMembershipsId() {
		return getLong("memberships_id");
	}

	public M setMembershipsDepartment(java.lang.String membershipsDepartment) {
		set("memberships_department", membershipsDepartment);
		return (M)this;
	}
	
	public java.lang.String getMembershipsDepartment() {
		return getStr("memberships_department");
	}

	public M setMembershipsSpecialty(java.lang.String membershipsSpecialty) {
		set("memberships_specialty", membershipsSpecialty);
		return (M)this;
	}
	
	public java.lang.String getMembershipsSpecialty() {
		return getStr("memberships_specialty");
	}

	public M setMembershipsDegree(java.lang.String membershipsDegree) {
		set("memberships_degree", membershipsDegree);
		return (M)this;
	}
	
	public java.lang.String getMembershipsDegree() {
		return getStr("memberships_degree");
	}

}
