package com.cyj.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseComputers<M extends BaseComputers<M>> extends Model<M> implements IBean {

	public M setComputersId(java.lang.Long computersId) {
		set("computers_id", computersId);
		return (M)this;
	}
	
	public java.lang.Long getComputersId() {
		return getLong("computers_id");
	}

	public M setComputersName(java.lang.String computersName) {
		set("computers_name", computersName);
		return (M)this;
	}
	
	public java.lang.String getComputersName() {
		return getStr("computers_name");
	}

	public M setComputersIp(java.lang.String computersIp) {
		set("computers_ip", computersIp);
		return (M)this;
	}
	
	public java.lang.String getComputersIp() {
		return getStr("computers_ip");
	}

	public M setReadRoomId(java.lang.Long readRoomId) {
		set("readRoomId", readRoomId);
		return (M)this;
	}
	
	public java.lang.Long getReadRoomId() {
		return getLong("readRoomId");
	}

	public M setComputersRemark(java.lang.String computersRemark) {
		set("computers_remark", computersRemark);
		return (M)this;
	}
	
	public java.lang.String getComputersRemark() {
		return getStr("computers_remark");
	}

}
