package com.cyj.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseStudents<M extends BaseStudents<M>> extends Model<M> implements IBean {

	public M setStudentsId(java.lang.Long studentsId) {
		set("students_id", studentsId);
		return (M)this;
	}
	
	public java.lang.Long getStudentsId() {
		return getLong("students_id");
	}

	public M setStudentsCardno(java.lang.String studentsCardno) {
		set("students_cardNo", studentsCardno);
		return (M)this;
	}
	
	public java.lang.String getStudentsCardno() {
		return getStr("students_cardNo");
	}

	public M setStudentsName(java.lang.String studentsName) {
		set("students_name", studentsName);
		return (M)this;
	}
	
	public java.lang.String getStudentsName() {
		return getStr("students_name");
	}

	public M setStudentsSex(java.lang.String studentsSex) {
		set("students_sex", studentsSex);
		return (M)this;
	}
	
	public java.lang.String getStudentsSex() {
		return getStr("students_sex");
	}

	public M setMembershipId(java.lang.Integer membershipId) {
		set("membershipId", membershipId);
		return (M)this;
	}
	
	public java.lang.Integer getMembershipId() {
		return getInt("membershipId");
	}

	public M setStudentsStatus(java.lang.Integer studentsStatus) {
		set("students_status", studentsStatus);
		return (M)this;
	}
	
	public java.lang.Integer getStudentsStatus() {
		return getInt("students_status");
	}

	public M setStudentsRemark(java.lang.String studentsRemark) {
		set("students_remark", studentsRemark);
		return (M)this;
	}
	
	public java.lang.String getStudentsRemark() {
		return getStr("students_remark");
	}

	public M setStudentsStuno(java.lang.String studentsStuno) {
		set("students_stuNo", studentsStuno);
		return (M)this;
	}
	
	public java.lang.String getStudentsStuno() {
		return getStr("students_stuNo");
	}

}
