package com.cyj.entity;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("computers", "computers_id", Computers.class);
		arp.addMapping("consumelogs", "consumelogs_id", Consumelogs.class);
		arp.addMapping("memberships", "memberships_id", Memberships.class);
		arp.addMapping("readrooms", "readrooms_id", Readrooms.class);
		arp.addMapping("sections", "sections_id", Sections.class);
		arp.addMapping("statistics", "statistics_id", Statistics.class);
		arp.addMapping("students", "students_id", Students.class);
		arp.addMapping("teachers", "teachers_id", Teachers.class);
	}
}

