package com.cyj.entity;

import com.cyj.entity.base.BaseComputers;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Computers extends BaseComputers<Computers> {
	public static final Computers dao = new Computers().dao();
}
