package com.cyj.entity;

import com.cyj.entity.base.BaseMemberships;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Memberships extends BaseMemberships<Memberships> {
	public static final Memberships dao = new Memberships().dao();
}
