package com.cyj.entity;

import com.cyj.entity.base.BaseReadrooms;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Readrooms extends BaseReadrooms<Readrooms> {
	public static final Readrooms dao = new Readrooms().dao();
}
