package com.cyj.entity;

import com.cyj.entity.base.BaseSections;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Sections extends BaseSections<Sections> {
	public static final Sections dao = new Sections().dao();
}
