package com.cyj.entity;

import com.cyj.entity.base.BaseStatistics;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Statistics extends BaseStatistics<Statistics> {
	public static final Statistics dao = new Statistics().dao();
}
