package com.cyj.entity;

import com.cyj.entity.base.BaseStudents;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Students extends BaseStudents<Students> {

	public static final Students dao = new Students().dao();

	//----------------以下是辅助处理日期格式化的工具类-------------------------------------------
		/**
		 * 格式化Student类中的日期格式
		 * @param list
		 * @return
		 */
		/*public static List<Student> format(List<Student> list){
			SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
			for(Student s:list){
				s.set("birthday", format.format(s.get("birthday")));
				s.set("updateTime", format.format(s.get("updateTime")));
			}		
			return list;
		}*/
		
		/**
		 * 格式化Student类中的日期格式
		 */
		/*public Student format(){
			SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
			this.set("birthday", this.get("birthday")!=null?format.format(this.get("birthday")):null);
			this.set("updateTime", this.get("updateTime")!=null?format.format(this.get("updateTime")):null);
			return this;
		}*/
}
