package com.cyj.entity;

import com.cyj.entity.base.BaseTeachers;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Teachers extends BaseTeachers<Teachers> {
	public static final Teachers dao = new Teachers().dao();
}
